name: Install GNU Fortran
description: Install & cache GNU Fortran
runs:
  using: composite
  steps:
    - name: Symlink to gfortran (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
        sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
        sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

    - name: Symlink to gfortran (MacOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo ln -fs /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
        sudo ln -fs /usr/local/bin/gcc-11 /usr/local/bin/gcc
        sudo ln -fs /usr/local/bin/g++-11 /usr/local/bin/g++

    - name: Workaround v20220626.1 gfortran executable run failures (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        FCDIR=/c/ProgramData/Chocolatey/bin
        LNDIR=/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin
        if [ -d "$FCDIR" ] && [ -f "$LNDIR/libgfortran-5.dll" ] && [ ! -f "$FCDIR/libgfortran-5.dll" ]; then
            ln -s "$LNDIR/libgfortran-5.dll" "$FCDIR/libgfortran-5.dll"
        fi

    - name: Print GNU compiler versions
      if: runner.os != 'Windows'
      shell: bash
      run: |
        gfortran --version
        gcc --version
        g++ --version

    - name: Print GNU compiler versions (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        gfortran --version
        gcc --version
        g++ --version