name: MODFLOW 6 integration testing
on:
  schedule:
    - cron: '0 6 * * *' # run at 6 AM UTC every day
jobs:
  test_compile_modflow:
    name: Compile modflow6
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        env: [ pip, miniconda, micromamba ]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6
          path: modflow6
      - name: Install gfortran
        uses: ./
      - name: Setup Python
        if: ${{ matrix.env == 'pip' }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Python dependencies
        if: ${{ matrix.env == 'pip' }}
        run: |
          pip3 install -r test/requirements.txt
      - name: Install miniconda environment
        if: ${{ matrix.env == 'miniconda' }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: modflow6/environment.yml
      - name: Install micromamba environment
        if: ${{ matrix.env == 'micromamba' }}
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: modflow6/environment.yml
          cache-downloads: true
          cache-env: true
      - name: Build modflow6
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson compile -v -C builddir
          meson install -C builddir